coverage:
    ignore:
        - "src/main/java/seedu/address/ui/*"
    status:
        patch:
            default:
                target: 0%
        project:
            default:
                target: 70%
