coverage:
    status:
        patch:
            default:
                target: 50%
                threshold: 5%
        project:
            default:
                target: auto
                threshold: 5%
ignore:
    - "src/main/java/seedu/address/ui/**/*"
